<?php
use Drupal\Core\Config\ConfigFactoryInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * @file
 * Primary module hooks for QE 410 module.
 */

/**
 * Implements hook_theme().
 */
function qe_410_theme($existing, $type, $theme, $path) {
  return [
    'qe_410_page_wrapper' => [
      'variables' => [
        'gone_title' => NULL,
        'gone_message' => NULL,
      ],
      'template' => 'qe-410-page',
    ],
    'qe_410_page_content' => [
      'variables' => [
        'gone_title' => NULL,
        'gone_message' => NULL,
      ],
      'template' => 'qe-410-page-content',
    ],

  ];
}



