<?php
use Drupal\Core\Config\ConfigFactoryInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * @file
 * Primary module hooks for QE 410 module.
 */

/**
 * Implements hook_theme().
 */function qe_410_theme($existing, $type, $theme, $path) {
  return [
    'qe_410_page' => [
      'variables' => [
        'qe_410_title' => NULL,
        'qe_410_markup' => NULL,
      ],
      'template' => 'qe-410-page',
    ],
  ];
}
